<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>{{ $title }}</title>
    <style>
        body { font-family: Arial, sans-serif; font-size: 9pt; color: #333; margin: 0; padding: 0; }
        .header { text-align: center; margin-bottom: 20px; border-bottom: 2pt solid #059669; padding-bottom: 10px; }
        .university-name { color: #059669; font-size: 15pt; font-weight: bold; margin: 0; }
        .university-address { color: #666; font-size: 9pt; margin: 2px 0; }
        h1 { color: #059669; font-size: 18pt; margin: 15px 0 5px 0; font-weight: bold; text-align: center; }
        .subtitle { color: #047857; font-size: 12pt; margin: 5px 0; font-weight: 600; text-align: center; }
        .report-meta { background-color: #f8f9fa; padding: 10px; font-size: 8.5pt; }
        .section { margin-bottom: 20px; }
        .section h2 { color: #059669; font-size: 12pt; margin-bottom: 10px; border-bottom: 1pt solid #059669; padding-bottom: 5px; }
        table.data-table { width: 100%; border-collapse: collapse; margin-bottom: 15px; }
        table.data-table th, table.data-table td { border: 1pt solid #ddd; padding: 5px; text-align: left; font-size: 7.5pt; }
        table.data-table th { background-color: #059669; color: white; font-weight: bold; font-size: 8pt; }
        .footer { margin-top: 30px; border-top: 1pt solid #ddd; padding-top: 10px; font-size: 7.5pt; color: #666; text-align: center; }
    </style>
</head>
<body>
    <div class="header">
        <table width="100%" cellpadding="0" cellspacing="0" border="0" align="center">
            <tr>
                <td width="30%" align="right">
                    <img src="{{ asset('images/SPUP-final-logo.png') }}" alt="SPUP Logo" width="80" height="80">
                </td>
                <td width="70%" align="left" style="padding-left: 15px;">
                    <div class="university-name">ST. PAUL UNIVERSITY PHILIPPINES</div>
                    <div class="university-address">Tuguegarao City, Cagayan, Philippines</div>
                </td>
            </tr>
        </table>

        <h1>{{ $title }}</h1>
        <div class="subtitle">In/Off Campus Activity Scheduling Information System</div>

        <div class="report-meta">
            <table width="100%" cellpadding="0" cellspacing="0" border="0">
                <tr>
                    <td width="50%" align="left">
                        <strong>Report Generated:</strong> {{ $generated_at->format('F d, Y \a\t g:i A') }}<br>
                        <strong>Academic Year:</strong> {{ date('Y') }}-{{ date('Y')+1 }}<br>
                        <strong>Analysis Period:</strong> {{ ucfirst($period) }} (from {{ $start_date->format('M d, Y') }})
                    </td>
                    <td width="50%" align="right">
                        <strong>Report Type:</strong> Statistics Report<br>
                        <strong>Data Points:</strong> {{ $statistics['activities_by_status']->sum('count') ?? 0 }} activities<br>
                        <strong>Generated By:</strong> {{ auth()->user()->name ?? 'System Administrator' }}
                    </td>
                </tr>
            </table>
        </div>
    </div>

    <div class="section">
        <h2>Activities by Status</h2>
        @if($statistics['activities_by_status']->count() > 0)
            <table class="data-table">
                <thead>
                    <tr>
                        <th>Status</th>
                        <th style="text-align: center;">Count</th>
                        <th style="text-align: center;">Percentage</th>
                    </tr>
                </thead>
                <tbody>
                    @php $total = $statistics['activities_by_status']->sum('count'); @endphp
                    @foreach($statistics['activities_by_status'] as $item)
                        <tr>
                            <td>
                                @if($item->workflow_status === 'approved_by_vp')
                                    Approved
                                @else
                                    {{ ucfirst(str_replace('_', ' ', $item->workflow_status)) }}
                                @endif
                            </td>
                            <td style="text-align: center;">{{ $item->count }}</td>
                            <td style="text-align: center;">{{ $total > 0 ? round(($item->count / $total) * 100, 1) : 0 }}%</td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        @else
            <p>No data available for this period.</p>
        @endif
    </div>

    <div class="section">
        <h2>Activities by Department</h2>
        @if($statistics['activities_by_department']->count() > 0)
            <table class="data-table">
                <thead>
                    <tr>
                        <th>Department</th>
                        <th style="text-align: center;">Count</th>
                        <th style="text-align: center;">Percentage</th>
                    </tr>
                </thead>
                <tbody>
                    @php $total = $statistics['activities_by_department']->sum('count'); @endphp
                    @foreach($statistics['activities_by_department'] as $item)
                        <tr>
                            <td>{{ $item->department ?? 'N/A' }}</td>
                            <td style="text-align: center;">{{ $item->count }}</td>
                            <td style="text-align: center;">{{ $total > 0 ? round(($item->count / $total) * 100, 1) : 0 }}%</td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        @else
            <p>No data available for this period.</p>
        @endif
    </div>

    <div class="section">
        <h2>Activities by Type</h2>
        @if($statistics['activities_by_type']->count() > 0)
            <table class="data-table">
                <thead>
                    <tr>
                        <th>Activity Type</th>
                        <th style="text-align: center;">Count</th>
                        <th style="text-align: center;">Percentage</th>
                    </tr>
                </thead>
                <tbody>
                    @php $total = $statistics['activities_by_type']->sum('count'); @endphp
                    @foreach($statistics['activities_by_type'] as $item)
                        <tr>
                            <td>{{ $item->type ?? 'N/A' }}</td>
                            <td style="text-align: center;">{{ $item->count }}</td>
                            <td style="text-align: center;">{{ $total > 0 ? round(($item->count / $total) * 100, 1) : 0 }}%</td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        @else
            <p>No data available for this period.</p>
        @endif
    </div>

    <div class="section">
        <h2>Monthly Trends</h2>
        @if($statistics['monthly_trends']->count() > 0)
            <table class="data-table">
                <thead>
                    <tr>
                        <th>Year</th>
                        <th>Month</th>
                        <th style="text-align: center;">Activities</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($statistics['monthly_trends'] as $item)
                        <tr>
                            <td>{{ $item->year }}</td>
                            <td>{{ date('F', mktime(0, 0, 0, $item->month, 1)) }}</td>
                            <td style="text-align: center;">{{ $item->count }}</td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        @else
            <p>No data available for this period.</p>
        @endif
    </div>

    <div class="footer">
        <p>This report was generated automatically by the SPUP Activity Management System.</p>
        <p>For questions or concerns, please contact the system administrator.</p>
    </div>
</body>
</html>
