<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>{{ $title }}</title>
    <style>
        body { font-family: Arial, sans-serif; font-size: 9pt; color: #333; margin: 0; padding: 0; }
        .header { text-align: center; margin-bottom: 20px; border-bottom: 2pt solid #059669; padding-bottom: 10px; }
        .university-name { color: #059669; font-size: 15pt; font-weight: bold; margin: 0; }
        .university-address { color: #666; font-size: 9pt; margin: 2px 0; }
        h1 { color: #059669; font-size: 18pt; margin: 15px 0 5px 0; font-weight: bold; text-align: center; }
        .subtitle { color: #047857; font-size: 12pt; margin: 5px 0; font-weight: 600; text-align: center; }
        .report-meta { background-color: #f8f9fa; padding: 10px; font-size: 8.5pt; }
        .filters { background-color: #f8f9fa; padding: 10px; font-size: 8.5pt; margin-bottom: 15px; }
        .filters h3 { margin: 0 0 5px 0; color: #059669; font-size: 10.5pt; }
        .summary-cell { text-align: center; padding: 10px; background-color: #f0fdf4; border: 1pt solid #bbf7d0; }
        .summary-number { font-size: 13.5pt; font-weight: bold; color: #059669; }
        .summary-label { font-size: 8pt; color: #047857; }
        table.data-table { width: 100%; border-collapse: collapse; margin-top: 15px; }
        table.data-table th, table.data-table td { border: 1pt solid #ddd; padding: 5px; text-align: left; vertical-align: top; font-size: 7.5pt; }
        table.data-table th { background-color: #059669; color: white; font-weight: bold; font-size: 8pt; }
        .footer { margin-top: 30px; border-top: 1pt solid #ddd; padding-top: 10px; font-size: 7.5pt; color: #666; text-align: center; }
    </style>
</head>
<body>
    <div class="header">
        <table width="100%" cellpadding="0" cellspacing="0" border="0" align="center">
            <tr>
                <td width="30%" align="right">
                    <img src="{{ asset('images/SPUP-final-logo.png') }}" alt="SPUP Logo" width="80" height="80">
                </td>
                <td width="70%" align="left" style="padding-left: 15px;">
                    <div class="university-name">ST. PAUL UNIVERSITY PHILIPPINES</div>
                    <div class="university-address">Tuguegarao City, Cagayan, Philippines</div>
                </td>
            </tr>
        </table>

        <h1>{{ $title }}</h1>
        <div class="subtitle">In/Off Campus Activity Scheduling Information System</div>

        <div class="report-meta">
            <table width="100%" cellpadding="0" cellspacing="0" border="0">
                <tr>
                    <td width="50%" align="left">
                        <strong>Report Generated:</strong> {{ $generated_at->format('F d, Y \a\t g:i A') }}<br>
                        <strong>Academic Year:</strong> {{ date('Y') }}-{{ date('Y')+1 }}<br>
                        <strong>Report Type:</strong> Users Report
                    </td>
                    <td width="50%" align="right">
                        <strong>Total Records:</strong> {{ $users->count() }}<br>
                        <strong>Report Type:</strong> Users Report<br>
                        <strong>Generated By:</strong> {{ auth()->user()->name ?? 'System Administrator' }}
                    </td>
                </tr>
            </table>
        </div>
    </div>

    @if(array_filter($filters))
        <div class="filters">
            <h3>Applied Filters:</h3>
            <strong>
            @if(!empty($filters['role'])) Role: {{ ucfirst($filters['role']) }} | @endif
            @if(!empty($filters['department'])) Department: {{ $filters['department'] }} | @endif
            @if(!empty($filters['status'])) Status: {{ ucfirst($filters['status']) }} @endif
            </strong>
        </div>
    @endif

    <table width="100%" cellpadding="0" cellspacing="10" border="0" style="margin-bottom: 20px;">
        <tr>
            <td class="summary-cell" width="14%">
                <div class="summary-number">{{ $summary['total_users'] }}</div>
                <div class="summary-label">Total Users</div>
            </td>
            <td class="summary-cell" width="14%">
                <div class="summary-number">{{ $summary['student_officers'] }}</div>
                <div class="summary-label">Student Officers</div>
            </td>
            <td class="summary-cell" width="14%">
                <div class="summary-number">{{ $summary['advisers'] }}</div>
                <div class="summary-label">Advisers</div>
            </td>
            <td class="summary-cell" width="14%">
                <div class="summary-number">{{ $summary['deans'] }}</div>
                <div class="summary-label">Deans</div>
            </td>
            <td class="summary-cell" width="14%">
                <div class="summary-number">{{ $summary['vp_acads'] }}</div>
                <div class="summary-label">VP Acads</div>
            </td>
            <td class="summary-cell" width="16%">
                <div class="summary-number">{{ $summary['director'] }}</div>
                <div class="summary-label">Director</div>
            </td>
            <td class="summary-cell" width="14%">
                <div class="summary-number">{{ $summary['psg_council_adviser'] }}</div>
                <div class="summary-label">PSG Council Adviser</div>
            </td>
        </tr>
    </table>

    @if($users->count() > 0)
        <table class="data-table">
            <thead>
                <tr>
                    <th width="30%">Name</th>
                    <th width="35%">Email</th>
                    <th width="15%">Role</th>
                    <th width="20%">Department</th>
                </tr>
            </thead>
            <tbody>
                @foreach($users as $user)
                    <tr>
                        <td>{{ $user->name }}</td>
                        <td>{{ $user->email }}</td>
                        <td>{{ $user->role === 'student' ? 'Student Officer' : ucfirst($user->role) }}</td>
                        <td>{{ $user->department ?? 'N/A' }}</td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    @else
        <div style="text-align: center; padding: 40px; color: #666; font-style: italic;">
            No users found matching the selected criteria.
        </div>
    @endif

    <div class="footer">
        <p>This report was generated automatically by the SPUP Activity Management System.</p>
        <p>For questions or concerns, please contact the system administrator.</p>
    </div>
</body>
</html>
